# Generated by Django 4.1.7 on 2026-01-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
