# Generated by Django 4.1.7 on 2026-01-29 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_card_generation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
