# Generated by Django 4.1.7 on 2026-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('student', 'date_of_report_card_generation'), name='unique_report_per_student_per_day'),
        ),
    ]
