# Generated by Django 4.1.7 on 2026-01-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_alter_reportcard_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportcard',
            name='unique_report_per_student_per_day',
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
